### PR TITLE
Update dependecies (Again...)

### PR DESCRIPTION
**Pull request by victor-rds**
This one is to fix my own PR #125, the requirement files contained the following sentence: 

_"To update, run: pip-compile --output-file=requirements.txt requirements.in/base.txt"_ 

But that was misleading, after reading `pip-tools` documentation I found that 

_"If pip-compile finds an existing requirements.txt file that fulfils the dependencies then no changes will be made, even if updates are available."_

That was my mistake, generated the files again and made new builds using python 3.10 that worked as expected. Once again sorry for the mistake!

### CODE REVIEW

**Review by tasn — APPROVED** [review]

**Comment by tasn** [comment]
Should I make a release?

**Comment by victor-rds** [comment]
Yes, but to be honest, I think you should "redo" last release and keep the change-log as it is now

**Comment by tasn** [comment]
What do you mean by redo? I can't unrelease.

**Comment by victor-rds** [comment]
Also this updates fixes 6 open CVEs, and stop comments like on #122 and #123

image

**Comment by tasn** [comment]
They don't actually apply to us except for the `low` one.

**Comment by victor-rds** [comment]
> What do you mean by redo? I can't unrelease.

I thought deleting the `v0.8.1` tag would remove the current release, if not possible make `v0.8.2` then, thanks!

> They don't actually apply to us except for the `low` one.

Yeah I know, I read your comments, but paranoid people will annoy you no matter what, this way everyone is satisfied with the security theater

**Comment by tasn** [comment]
Oh yeah, 100%. :)

I have no problem with updating dependencies, I'm not against it. Just don't think it's a cause for such alarm.

> I thought deleting the v0.8.1 tag would remove the current release, if not possible make v0.8.2 then, thanks!

We try not to rewrite history, so not change what's already released. So I'll just publish v0.8.2.

**Pull request merged**
