### PR TITLE
Fix pydantic update

### PR DESCRIPTION
**Pull request by Focshole**
Fixes issue #170. Please test it if it works for you too.

### CODE REVIEW

**Comment by Focshole** [comment]
This is just the tip of the iceberg, many requests still failed

**Comment by tasn** [comment]
I think we just don't currently support pydantic v2 (not sure whether fastapi does or not), but this is a project of its own to figure this out.

**Comment by tasn** [comment]
Have you tried running the tests?

**Comment by Focshole** [comment]
Nope sorry, i just tried to quickly hot fix the code, but I got no success overall. Since around the 16th of sept my local etesync installation stopped working after a system update and I just realized about it.

**Comment by tasn** [comment]
I'd really recommend a Docker installation or a virtualenv. Unfortunately projects in the Python/node/etc. ecosystems evolve (read: break API) quite often, and because distros are always up to date, it makes maintenance hell. Because I also don't want to force people to update the the most recent version of everything (e.g. because of Debian). So it's just a pain all around.

**Comment by Focshole** [comment]
I'll try to migrate the data on docker then, thank you! :)
I hope that just mounting the existent data folder would suffice 🤞

**Comment by tasn** [comment]
@Focshole, yeah, that should suffice. You can also do a virtualenv (no docker).

**Comment by Focshole** [comment]
It worked! I'd add a comment on the AUR version, because it is causing https://github.com/etesync/server/issues/170 !

**Comment by tasn** [comment]
Ah damn, AUR, yeah. Need to try to figure out how to maybe support both.

**Pull request closed without merging**
