### PR TITLE
Update dependencies for Python 3.11

### PR DESCRIPTION
**Pull request by victor-rds**
The `httptools` and `uvloop` packages failed to build when using Python 3.11, both have been fixed newer versions, so I took the opportunity to done the same to all dependencies.

Also updated the test server base image to `python:3.11.0-alpine` for testing the changes.

### CODE REVIEW

**Review by tasn — APPROVED** [review]

**Comment by tasn** [comment]
Thanks a lot!

**Comment by victor-rds** [comment]
@tasn could you make a new release? I use master for myself, but also release numbered versions that track this repository, just so I don't accidentally break someone server :sweat_smile:, akin to stable releases

**Comment by tasn** [comment]
I always forget! One moment.

**Comment by tasn** [comment]
Done.

**Pull request merged**
