### PR TITLE
Replace aioredis with redis-py

### LINKED ISSUE #150: Gentoo: aioredis to redis-py
Hi,
I’ve noticed recently that on Gentoo, aioredis is being removed with redis-py as a replacement.
How should I deal with this?
Should I patch the server myself to replace occurences or should we work together to change lib?
I dont know if aioredis maintenance is going to end upstream or not.
All advises are welcome.
```
- dev-python/aioredis-2.0.1::gentoo (masked by: package.mask)
/var/db/repos/gentoo/profiles/package.mask:
# Michał Górny <mgorny@gentoo.org> (2022-07-25)
# aioredis has been integrated in >=dev-python/redis-py-4.2.0.
# No revdeps.
# Removal on 2022-08-24.  Bug #860840.
```

### PR DESCRIPTION
**Pull request by Xiretza**
`aioredis` has been merged into `redis-py` and will no longer be maintained as a separate project.

Fixes #150.

### CODE REVIEW

**Comment by Xiretza** [comment]
Unfortunately I don't have a redis setup to actually test this thoroughly, so it'd be great if someone else could give it a go.

**Comment by tasn** [comment]
Oh, good to know! Let me know once this has been properly tested. I also don't have time for at least a week. :(

**Comment by tasn** [comment]
It's not the end of the world not to use a pool, but it's much much better.

**Comment by tasn** [comment]
Actually, I take it back. I think with pub/sub, which we use, it's probably a big deal.

**Comment by tasn** [comment]
Yeah, I understood that @jman-schief, though thanks for the clarification. I just re-emphasized, that I think a pool is needed, or at least the code needs to be changed to reconnect every time (less than ideal).

**Comment by tasn** [comment]
OK, it looks like redis-py does indeed support pooling, we just need to slightly change how we create the object (as discussed above).

@Xiretza, got time to take a look, or should I see if I can adjust this PR?

**Comment by tasn** [comment]
I pushed the adjustments to `Xiretza-redis-py` on this repo. Can you pull the changes and add to this PR? I'll happily merge it after.

**Review by tasn — APPROVED** [review]

**Comment by victor-rds** [comment]
@tasn could you make a new release?

**Comment by tasn** [comment]
Done! Thanks @victor-rds for the reminder. In my head you're still tracking `master`. :)

**Pull request merged**
