### PR TITLE
Update Dependencies

### PR DESCRIPTION
**Pull request by victor-rds**
Django version pinned below 4.0 in the `requirements.in` files, updated all other dependencies and execute `pip-compile`.

Also add `DEFAULT_AUTO_FIELD = 'django.db.models.AutoField'` to remove models.W042 warnings.

### CODE REVIEW

**Review by tasn — APPROVED** [review]
Good call!

**Comment by tasn** [comment]
Should I release 0.8.1?

**Comment by victor-rds** [comment]
Yes, the v0.8.0 automated build failed, so let's try again.

**Comment by tasn** [comment]
Done.

**Pull request merged**
